# Generated by Django 5.2.8 on 2025-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_blogtitle_delete_blogposts_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blogtitle',
            old_name='title',
            new_name='text',
        ),
    ]
