# Generated by Django 5.2.8 on 2025-12-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_topic_post_delete_blogpost_delete_blogtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='topic',
        ),
    ]
